dist: focal

notifications:
  email:
    - mum4k-ci@elohim.sk

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - pkg-config
      - python
      - python3-pip
      - unzip
      - wget
      - zip

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/6.0.0/bazel_6.0.0-linux-x86_64.deb
  - sha256sum -c bazel/bazel_6.0.0-linux-x86_64.deb.sha256
  - sudo dpkg --force-all -i bazel_6.0.0-linux-x86_64.deb
  - sudo /usr/bin/pip install platformio

script:
  - bazel build //...
  - bazel test //...
